### ISSUE TITLE
Having issue where photo index evaluates to Infinity

### ISSUE THREAD

**Issue by JamesWatling** [halilb/react-native-photo-browser#12] opened 2016-07-28 07:18 UTC
Hi!

Firstly, thanks for the amazing package very useful - love it.

I have been using parts of this in a way that it maybe wasn't entirely intended and I have encountered an error with the `onScroll` method.

My use case is showing the images in a grid of my own, that on clicking creates a new `<PhotoBrowser` element starting the index with the image that was touched.

This all works great but I get into a weird state where the component is rendered one extra time and this time it causes a error, 
![image](https://cloud.githubusercontent.com/assets/2044104/17204017/8cdd180c-54d5-11e6-942a-a38e3cd3c8bf.png)

I have tracked it down to the `_onScroll()` function specifically `event.layoutMeasurement.width` in some cases evaluates to `0` and then of course we divide by 0 somewhere (Infinity) and then the library tries to look at the image at index Infinity.

My temporary work around is to set the value to 
`const layoutWidth = event.layoutMeasurement.width || Dimensions.get('window').width;` which ensures that everything works as expected - this has been tested on iPhone 4s, 5, 5c, 5s, 6, 6s and several android phones, and works as expected.

I have forked this so I can use it in my project, but would like to see if you have a more elegant solution or ideas of the bigger issue.

Thanks

**Comment by 1st8** [comment] 2016-08-05 13:55
Hey,

I am having the same issue - using the `initialIndex` prop leads to the error message you posted above on opening rendering the component and also on selecting an image from the grid.
I am having this problem exclusively on IOS, not on android.
However, i don't understand how this is related to the infinite `width` fix you mentioned.
It looks like `this.state.currentMedia` is somehow undefined in the `FullScreenContainer`.

Maybe there is a quick fix for this, after dismissing the error message, the right image is shown anyhow.

Cheers

**Comment by halilb** [comment] 2016-08-12 17:44
Hey @JamesWatling, sorry for my late answer and thank you for your time and contribution.

Could you also create a new row in the Example project that reproduces the problem you're experiencing? I'll try creating one if it's not practical for you to create it.

**Comment by bharath-kamath** [comment] 2016-10-26 07:50
I agree with @1st8 , the issue seems to be with currentMedia being undefined. For now I re-order the list so that selected image is first, will try to get a PR for this if i can manage to fix this. Has anybody managed to fix this yet?

**Comment by halilb** [comment] 2017-07-22 14:20
This should be fixed with #13.

**Closed by halilb** 2017-07-22 14:20 UTC
